### ISSUE TITLE
SnakeYAML old dependency

### ISSUE THREAD

**Issue by wbervoets** [DroidsOnRoids/mockwebserver-path-dispatcher#23]
Why is this library depending on an old forked SnakeYaml 1.18 ?

https://bitbucket.org/asomov/snakeyaml/wiki/Changes - with classifier "android" it should be fine to be able to use the latest version?

**Comment by koral--** [comment]
Yeah, there was that classifier, IIRC even at the time of releasing the first version with forked copy.
It was due to this issue: https://bitbucket.org/asomov/snakeyaml/issues/325/failing-on-android which is still open.
snakeyaml used in this library is, in turn a fork of another another fork: https://github.com/bmoliveira/snake-yaml see description there for more details.

Apart from that probably nobody interested in this project follows changes in the upstream snakeyaml repo since there is no real need to update YAML parsing. No known bug, performance issue, missing feature etc. related to YAML parsing.

If you believe that we can update snakeyaml version to original one (and it really works on Android) feel free to create a PR.

**Comment by wbervoets** [comment]
I think it should work. Before using your path dispatcher I used the latest snakeyaml version in my android instrumentation test to parse a yaml response. After including your library I had duplicate classes errors, that's how I found out that two different versions were in my dependencies.

I'll try to find some time this week to look into a PR

**Comment by koral--** [comment]
Go ahead, if original version works, we'll be happy to switch to it.
